name: Release bot

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  minify-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'  # Use the appropriate Python version

      - name: Install dependencies
        run: |
          pip install black  # Install black for formatting
          
      - name: Get commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV
          SHORT_SHA=$(git rev-parse --short=7 HEAD)  # Get the first 7 characters of the commit SHA
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
          
      - name: Format Python files
        run: |
          mkdir -p formatted
          black pico_w/Gameberry --quiet --exclude 'pico_w/Gameberry/.*\.py' --skip-string-normalization --line-length 79 --target-version py311 --fast
          cp -r pico_w/Gameberry formatted

      
      - name: Zip minified files
        run: zip -r pico_w.zip formatted

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: '${{ env.SHORT_SHA }}'
          release_name: '${{ github.sha }}'
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pico_w.zip
          asset_name: pico_w.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
